---
- name: Install MySQL Workbench on Windows
  hosts: windows_servers
  gather_facts: no

  roles:
    - role: MySQL_Workbench_Role
      tasks_from: 1.Install_NetFramework
    - role: MySQL_Workbench_Role
      tasks_from: 2.Install_Packages
    - role: MySQL_Workbench_Role
      tasks_from: 3.Install_MySQL_Workbench