---
- name: Install MySQL Workbench on Windows
  hosts: windows_servers
  gather_facts: no

  roles:
    - role: MySQL_Workbench_Role
      tasks_from: tasks/1.Install_NetFramework.yml
    - role: MySQL_Workbench_Role
      tasks_from: tasks/2.Install_Packages.yml
    - role: MySQL_Workbench_Role
      tasks_from: tasks/3.Install_MySQL_Workbench.yml

    tasks:
      - name: Install MySQL Workbench
      win_chocolatey:
        name: mysql.workbench
        version: '8.0.36'
        source: https://community.chocolatey.org/api/v2/
        state: present    