---
- name: Install MySQL Workbench on Windows
  hosts: windows_servers
  gather_facts: no

  roles:
    - MySQL_Workbench_Role  

  tasks:

    - name: Download installer if it doesn't exist
      win_shell: |
        $installerPath = "C:\\Temp\\mysql-workbench.msi"
        if (-Not (Test-Path $installerPath)) {
            Invoke-WebRequest -Uri "https://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-workbench-community-8.0.36-winx64.msi" -OutFile $installerPath
        }
      args:
        executable: powershell.exe        