---
- name: Install MySQL Workbench on Windows
  hosts: windows_servers
  gather_facts: no

  roles:
    - MySQL_Workbench_Role\tasks\1.Install_NetFramework.yml
    - MySQL_Workbench_Role\tasks\2.Install_Packages.yml
    - MySQL_Workbench_Role\tasks\3.Install_MySQL_Workbench.yml

  tasks:
