---
- name: Check and Install MySQL Workbench using Chocolatey
  hosts: win_dr_server
  become_method: winrm

  tasks:
    - name: Gather Chocolatey facts
      community.windows.win_product_facts:
      
    - name: Check if MySQL Workbench is installed
      ansible.builtin.debug:
        var: ansible_facts['ansible_chocolatey']['packages']['mysql.workbench']

    - name: Install MySQL Workbench if not installed
      ansible.windows.win_chocolatey:
        name: mysql.workbench
        state: present
