---
- name: Install Wordpress
  hosts: webservers
  become: true
  vars_files:
    - Wordpress_Server_Role/vars/default.yml
    - Wordpress_Server_Role/vars/secrets.yml

  roles:
    - name: Wordpress_Server_Role
