---
- name: Verify C:\Temp folder existence
  ansible.windows.win_stat:
    path: C:\Temp
  register: temp_folder

- name: Create C:\Temp folder if it doesn't exist
  ansible.windows.win_file:
    path: C:\Temp
    state: directory
  when: not temp_folder.stat.exists

- name: Verify file existence
  ansible.windows.win_stat:
    path: C:\Temp\mysql-workbench.msi
  register: workbench_installer

- name: Download installer if it doesn't exist
  win_shell: |
    $installerPath = "C:\\Temp\\mysql-workbench.msi"
    if (-Not (Test-Path $installerPath)) {
        Invoke-WebRequest -Uri "https://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-workbench-community-8.0.36-winx64.msi" -OutFile $installerPath
    }
  args:
    executable: powershell.exe

- name: Download Visual C++ Redistributable
  ansible.windows.win_get_url:
    url: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
    dest: C:\Temp\vc-redist.exe