---
- name: Creating a temporary folder
  ansible.windows.win_file:
    path: C:\Temp
    state: directory

- name: Download .NET Framework 4.5.2
  ansible.windows.win_get_url:
    url: https://download.microsoft.com/download/E/2/1/E21644B5-2DF2-47C2-91BD-63C560427900/NDP452-KB2901907-x86-x64-AllOS-ENU.exe
    dest: C:\Temp\net-framework-4.5.2.exe

- name: Download Visual C++ Redistributable
  ansible.windows.win_get_url:
    url: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
    dest: C:\Temp\vc-redist.exe


- name: Download MySQL Workbench installer
  win_get_url:
    url: "https://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-workbench-community-8.0.26-winx64.msi"
    dest: C:\Temp\mysql-workbench.msi
