---
- name: Creating a temporary folder
  win_file:
    path: C:\Temp
    state: directory

- name: Download .NET Framework 4.5.2
  win_get_url:
    url: https://www.microsoft.com/en-US/download/details.aspx?id=42642
    dest: C:\Temp\net-framework-4.5.2.exe

- name: Download Visual C++ Redistributable
  win_get_url:
    url: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
    dest: C:\Temp\vc-redist.exe


- name: Download MySQL Workbench installer
  win_get_url:
    url: https://downloads.mysql.com/archives/get/p/8/file/mysql-workbench-community-8.0.34-winx64.msi
    #url: https://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-workbench-community-8.0.36-winx64.msi
    dest: C:\Temp\mysql-workbench-installer.msi
