---
- name: Setup SSH Key and Git Repository
  hosts: ansible_servers
  gather_facts: no
  become: yes

  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"  # Disable strict host key checking
    ansible_ssh_private_key_file: "~/.ssh/{{ GH_key_name }}"
    vault_email_address: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              30646565653764333437623130303538323462303736343462303737303637653464336238383664
              3463303436643434303937653836316638613032623262640a343866396535363462653232343632
              39383839393735363434656663306135313137346461336535653133303861366135346439396638
              3436646234313762380a386464333831623232393136333564306139366364633031316562643933
              32636232363862396439383361346663663832613134323032666534303634643238

    GH_key_name: "{{ 'AnsibleGH_Prod' if 'ansible_prod' in group_names else 'AnsibleGH_DR' }}"

  tasks:
    - name: Update and upgrade repos
      apt:
        update_cache: yes
        upgrade: yes
      when: ansible_os_family == 'Debian'



    - name: Install ansible
      package:
        name: ansible
        state: present

    - name: Generate SSH key
      shell: ssh-keygen -t ed25519 -C "{{ vault_email_address }}" -f ~/.ssh/{{ GH_key_name }} -N ""
      args:
        creates: "~/.ssh/{{ GH_key_name }}"
      register: ssh_keygen_output

    - name: Print SSH public key
      debug:
        var: ssh_keygen_output.stdout

    - name: Start SSH agent
      shell: eval "$(ssh-agent -s)"

    - name: Add SSH key to SSH agent
      shell: ssh-add ~/.ssh/{{ GH_key_name }}

    - name: Create SSH config file
      blockinfile:
        path: ~/.ssh/config
        block: |
          Host github.com
            IdentityFile ~/.ssh/{{ GH_key_name }}
            IdentitiesOnly yes

    - name: Create Grupo2 folder and clone repository
      file:
        path: ~/Grupo2
        state: directory
      git:
        repo: git@github.com:sirgeadas/Projeto-Ansible_LSF.git
        dest: ~/Grupo2
