
#- name: Download .NET Framework 4.8
#  win_get_url:
#    url: "https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48"
#    dest: C:\Temp\dotnet48.exe

#- name: Install .NET Framework 4.8
#  win_shell: |
#    Start-Process -Wait -FilePath C:\Temp\dotnet48.exe -ArgumentList "/q /norestart"

- name: Download Chocolatey Installer
  win_get_url:
    url: "https://chocolatey.org/install.ps1"
    dest: C:\Temp\install_choco.ps1

- name: Run Chocolatey Installer
  win_shell: |
    Set-ExecutionPolicy Bypass -Scope Process -Force
    . C:\Temp\install_choco.ps1
  args:
    executable: powershell.exe


- name: Reboot the system
  win_reboot:
    reboot_timeout: 200

- name: Install Microsoft Visual C++ Redistributable for Visual Studio 2015-2022
  win_chocolatey:
    name: vcredist140
    version: '14.38.33135'
    source: https://community.chocolatey.org/api/v2/
    state: present

- name: Install MySQL Workbench
  win_chocolatey:
    name: mysql.workbench
    version: '8.0.36'
    source: https://community.chocolatey.org/api/v2/
    state: present       
    
