---
- name: Install Firefox and BGinfo
  hosts: windows_servers
  gather_facts: true

  tasks:
    - name: Installing Firefox
      win_chocolatey:
        name: firefox
        state: present

    - name: Creating an temporary folder
      win_file:
        path: C:\Temp
        state: directory  

    - name: Downloading BGinfo
      win_get_url:
        url: https://download.sysinternals.com/files/BGInfo.zip
        dest: C:\Temp\bginfo.zip

    - name: Extracting BGinfo
      win_unzip:
        src: C:\Temp\bginfo.zip
        dest: C:\Temp\bginfo

    - name: Creating BGinfo's folder 
      win_file:
        path: C:\Program Files\BGinfo
        state: directory  

    - name: Copying BGinfo to Program Files
      win_copy:
        src: C:\Temp\bginfo\Bginfo64.exe
        dest: C:\Program Files\BGinfo\Bginfo64.exe
        remote_src: yes

    - name: Create BGinfo shortcut
      win_shortcut:
        src: C:\Program Files\BGinfo\Bginfo64.exe
        dest: "{{ ansible_env.USERPROFILE }}\\Desktop\\BGinfo64.lnk"

   # - name: Set BGinfo configuration
   #   win_command: 'C:\Program Files\BGinfo\bginfo.exe C:\Program Files\BGinfo\config.bgi /timer:0 /nolicprompt'

    - name: Clean up temporary files
      win_file:
        path: C:\Temp
        state: absent
        recurse: yes