---
- name: Check missing updates
  win_updates: state=searched
  register: update_count

- name: List missing updates
  debug: var=update_count

- name: Install updates
  win_updates:
    category_names: "{{ Windows_Updates }}"
    log_path: C:\\Ansible_Windows_Update_Log.txt
  register: updates

- name: Detail Updates
  debug:
    var: updates

- name: Restart the system if it is necessary
  win_reboot:
  when: updates.reboot_required

