---
- name: Clone The Project Ansible Repository
  hosts: ansible_servers
  gather_facts: yes
 
  tasks:
    - name: Clone repository
      git:
        repo: git@github.com:sirgeadas/Projeto-Ansible_LSF.git
        dest: "{{ ansible_env.HOME }}/Projeto-Ansible_LSF"
        clone: yes
        update: yes