galaxy_info:
  author: Sara Peres, Ludmilla Guimarães e Filipe Geadas
  description: This role installs MySQL Workbench on a Windows machine. 
  company: UpSkill


  license: GPL

  min_ansible_version: 2.1
  galaxy_tags: [MySQL, MySQL Workbench, LSF, UPskill]

dependencies: []
# No dependencies needed for this role.