---
# handlers file for Playbooks_and_Roles/Wordpress_Server_Role
- name: Reload Apache
  service:
    name: apache2
    state: reloaded
    
- name: Restart Apache
  service:
    name: apache2
    state: restarted