---
- name: Include variable for user, password and database name
  include_vars: secrets.yml

- name: Update repository cache
  apt: 
    update_cache: yes

- name: Install mysql-server, python3-pymyslq e python3-pip
  apt:
    name: 
      - mysql-server
      - python3-pymysql
      - python3-pip

- name: Make sure the service is up and running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Setting mysql_secure_installation
  expect:
    command: mysql_secure_installation
    responses:
      'Enter password for user root': "{{root_password}}"
      'VALIDATE PASSWORD component?': ''
      'Change the password for root ?': ''
      'Remove anonymous users?': 'y'
      'Disallow root login remotely?': 'n'
      'Remove test database and access to it?': 'y'
      'Reload privilege tables now?': 'y'
    timeout: 1
  environment:
    MYSQL_PWD: "{{root_password}}"
  register: mysql_secure

- name: Configure root password
  mysql_user:
    name: root
    password: "{{root_password}}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: localhost
    login_user: root
    login_password: '{{root_password}}'
    state: present

- name: Create database
  mysql_db:
    name: "{{db_name}}"
    state: present
    login_user: root
    login_password: "{{root_password}}"
    encoding: utf8mb4
    collation: utf8mb4_bin

- name: Create admin user to remote access
  mysql_user:
    name: "{{admin_user}}"
    password: "{{admin_password}}"
    priv: 'Wordpress.*:ALL,GRANT'
    host: '%'
    append_privs: true
    login_user: root
    login_password: "{{root_password}}"
    state: present


- name: Change to 1 the variable log_bin_trust_function_creators
  lineinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    line: "log-bin-trust-function-creators = 1"

- name: Change bind-address in MySQL config
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'    
  notify: 
  - Restart MySQL

