---
- name: Atualização de Sistema Operacional
  hosts: all
  become: yes

  tasks:
    - name: Update para sistemas Linux
      when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"
      yum:
        name: '*'
        state: latest
      apt:
        upgrade: "dist"

    - name: Run Windows Updates
      win_updates:
        roles:
    - OS-Update_Role

      

      



