---
- name: Uninstall MySQL server and all of its folders/dependencies
  hosts: dbservers
  become: yes

  tasks:
    - name: Remove mysql-server and mysql-server-8.0 packages
      apt:
        name:
          - mysql-server
          - mysql-server-8.0
        state: absent
        purge: yes

    - name: Autoremove unnecessary packages
      command: apt-get autoremove -y

    - name: Autoclean package cache
      command: apt-get autoclean -y

    - name: Remove MySQL configuration directory
      file:
        path: /etc/mysql
        state: absent

    - name: Remove MySQL data directory
      file:
        path: /var/lib/mysql
        state: absent

    - name: Ensure /etc/mysql/conf.d/ directory exists
      file:
        path: /etc/mysql/conf.d/
        state: directory
        mode: '0755'